spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationInSeconds: 7200 # 2h
    refreshTokenExpirationInSeconds: 604800 # 7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
