spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 6886375
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationInSeconds: 1800 # 5m
    refreshTokenExpirationInSeconds: 604800 # 7d